/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAccept {
        "id": string;
    }
    interface AppConfig {
    }
    interface AppDetail {
        "id": string;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppTabs {
    }
}
declare global {
    interface HTMLAppAcceptElement extends Components.AppAccept, HTMLStencilElement {
    }
    var HTMLAppAcceptElement: {
        prototype: HTMLAppAcceptElement;
        new (): HTMLAppAcceptElement;
    };
    interface HTMLAppConfigElement extends Components.AppConfig, HTMLStencilElement {
    }
    var HTMLAppConfigElement: {
        prototype: HTMLAppConfigElement;
        new (): HTMLAppConfigElement;
    };
    interface HTMLAppDetailElement extends Components.AppDetail, HTMLStencilElement {
    }
    var HTMLAppDetailElement: {
        prototype: HTMLAppDetailElement;
        new (): HTMLAppDetailElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {
    }
    var HTMLAppTabsElement: {
        prototype: HTMLAppTabsElement;
        new (): HTMLAppTabsElement;
    };
    interface HTMLElementTagNameMap {
        "app-accept": HTMLAppAcceptElement;
        "app-config": HTMLAppConfigElement;
        "app-detail": HTMLAppDetailElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-tabs": HTMLAppTabsElement;
    }
}
declare namespace LocalJSX {
    interface AppAccept {
        "id"?: string;
    }
    interface AppConfig {
    }
    interface AppDetail {
        "id"?: string;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface IntrinsicElements {
        "app-accept": AppAccept;
        "app-config": AppConfig;
        "app-detail": AppDetail;
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-tabs": AppTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-accept": LocalJSX.AppAccept & JSXBase.HTMLAttributes<HTMLAppAcceptElement>;
            "app-config": LocalJSX.AppConfig & JSXBase.HTMLAttributes<HTMLAppConfigElement>;
            "app-detail": LocalJSX.AppDetail & JSXBase.HTMLAttributes<HTMLAppDetailElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tabs": LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
        }
    }
}
